### ISSUE TITLE
delaware is missing

### ISSUE THREAD

**Issue by alensubasic** [propublica/stateface#11]
http://en.wikipedia.org/wiki/Delaware

**Comment by thejefflarson** [comment]
It's a capital H: http://propublica.github.io/stateface/#font-map

**Comment by alensubasic** [comment]
ah sorry I was looking here http://propublica.github.io/stateface/reference/cssclass.html

**Comment by thejefflarson** [comment]
ah ok, yeah i'll fix that, FWIW it is in the css too.

**Comment by alensubasic** [comment]
Thanks! Have a good weekend!

**Comment by thejefflarson** [comment]
cool shld be fixed now 

http://propublica.github.io/stateface/reference/cssclass.html 

hopefully it makes biden happy:

<img src="http://media4.s-nbcnews.com/i/streams/2014/December/141208/1D274907376164-today-sad-biden-141208-tease.jpg">
