### ISSUE TITLE
Sass for stateface

### ISSUE THREAD

**Issue by amurrell** [propublica/stateface#12]
I don't know if this is appropriate (creating an issue), but I wrote sass for this and put it on my gist. You can have it to do with it as you please... perhaps it will be useful to someone:

https://gist.github.com/amurrell/e608eb312f35e5532b6c

**Comment by thejefflarson** [comment]
That's great! Create a pull request that puts it in the reference folder, and an explanation of in this section:

https://github.com/propublica/stateface/blob/master/reference/reference.mdown#css-replacement

and I'll merge?
