### ISSUE TITLE
Documentation Link Stylesheet

### ISSUE THREAD

**Issue by amurrell** [propublica/stateface#14]
Hey, 

If you don't link the generated stylesheet, the section examples for Sass won't work. It seems that was removed from the merge.

`<link rel="stylesheet" href="reference/stateface-generated.css" type="text/css">`

**Comment by thejefflarson** [comment]
oh my bad. I was working quickly.

**Comment by amurrell** [comment]
No worries, thanks for including the Sass stuff :)
